access_key = "***"
secret_key = "***"
region     = "ap-south-1"
vpc_name   = "TEST_VPC"
cidr_block = "10.0.0.0/16"

ami_id               = "value"
instance_type        = "t2.micro"
key_name             = "test-key"
public_key_file_name = "test-key.pub"